# For ElasticSearch servers
---
- hosts: final_elasticsearch
  remote_user: ubuntu
  gather_facts: no
  become: yes
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: install git
      apt:
        name: git
    - name: Delete /var/www/ for the git checkout
      shell: sudo rm -rf /var/www/
    - name: Get git checkout
      git:
        repo: 'https://github.com/dmu1313/CSE356P3.git'
        dest: /var/www/
####   Start Elasticsearch stuff   ####
    - name: Install jdk 8
      apt:
        name: openjdk-8-jre
        update_cache: yes
    - name: Get key for Elastic packages
      shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    - name: Get apt-transport-https
      apt:
        name: apt-transport-https
    - name: Save repository for Elastic packages.
      shell: |
        echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
    - name: Get Elastic Search
      apt:
        name: elasticsearch
        update_cache: yes
    - name: Elastic search config
      shell: |
        sudo mv /var/www/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
        sudo systemctl restart elasticsearch
        sudo chmod 777 /etc/elasticsearch
        sudo chmod 777 /var/log/elasticsearch
