# For main server (load balancer)
---
- hosts: final_main
  remote_user: ubuntu
  gather_facts: no
  become: yes
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
######    Nginx and Git    #######
    # - name: Install Nginx
    # apt:
    #   name: nginx
    #   update_cache: yes
    #   state: latest
    # - name: install git
    #   apt:
    #     name: git
    - name: Delete /var/www/ for the git checkout
      shell: sudo rm -rf /var/www/
    - name: Get git checkout
      git:
        repo: 'https://github.com/dmu1313/CSE356P3.git'
        dest: /var/www/
    - name: Set up reverse proxy load balancer Nginx
      shell: |
        sudo mv /var/www/rest_proxy.conf /etc/nginx/rest_proxy.conf
        sudo mv /var/www/nginx.conf /etc/nginx/nginx.conf
        sudo systemctl restart nginx
#############    Node    ##############
    # - name: Download Nodejs 11.x
    #   shell: |
    #     sudo curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
    #     sudo apt-get install -y nodejs
#############    npm packages    ##############
    - name: Init npm in project directory
      shell: |
        cd /var/www/server/
        sudo npm init -y
      args:
        chdir: /var/www/server/
    - name: Install Express JS
      npm:
        name: express
        global: no
        path: /var/www/server/
    - name: Install NodeMailer
      npm:
        name: nodemailer
        global: no
        path: /var/www/server/
    - name: Install Cookie-Parser
      npm:
        name: cookie-parser
        global: no
        path: /var/www/server
    - name: Install MongoDB npm package
      npm:
        name: mongodb
        global: no
        path: /var/www/server
    - name: Install util npm package
      npm:
        name: util
        global: no
        path: /var/www/server
    - name: Install ElasticSearch npm package
      npm:
        name: "@elastic/elasticsearch"
        global: no
        path: /var/www/server
    - name: Install cassandra driver
      npm:
        name: cassandra-driver
        global: no
        path: /var/www/server/
    - name: Install formidable
      npm:
        name: formidable
        global: no
        path: /var/www/server/
    - name: Install memcached Node client
      npm:
        name: memcached
        global: no
        path: /var/www/server
    - name: Install amqplib
      npm:
        name: amqplib
        global: no
        path: /var/www/server/
######    Postfix Email Server    ########
    # - name: Install Postfix
    #   apt:
    #     name: postfix
    # - name: Configure Postfix
    #   shell: |
    #     sudo mv /var/www/main.cf /etc/postfix/main.cf
    #     sudo systemctl restart postfix