# For memcached servers
---
- hosts: final_memcached
  remote_user: ubuntu
  gather_facts: no
  become: yes
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: Install memcached
      apt:
        name: memcached
        update_cache: yes
    - name: Copy over memcached configuration file
      shell: |
        sudo mv /var/www/memcached.conf /etc/memcached.conf
    # memcached configuration file stored at /etc/memcached.conf