# Meant for a one time setup for the older API servers that need mongos
---
- hosts: final_mongos
  remote_user: ubuntu
  gather_facts: no
  become: yes
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
    - name: One time setup for MongoDB
      shell: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
        echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
        sudo apt-get update
    - name: One time install for MongoDB
      apt:
        name: mongodb-org
    - name: Start mongos.
      shell: |
        sudo chmod 777 /var/log/mongodb
        mongos --config /var/www/MongoMongos.conf --fork --logpath /var/log/mongodb/mongos.log --quiet