# For MongoDB Shard servers
---
- hosts: final_mongo_shard
  remote_user: ubuntu
  gather_facts: no
  become: yes
  pre_tasks:
    - name: update
      apt:
        update_cache: yes
  tasks:
####      Setup Git      ########
    - name: install git
      apt:
        name: git
    - name: Delete /var/www/ for the git checkout
      shell: sudo rm -rf /var/www/
    - name: Get git checkout
      git:
        repo: 'https://github.com/dmu1313/CSE356P3.git'
        dest: /var/www/
#####    Setup MongoDB    #########
    - name: One time setup for MongoDB
      shell: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
        echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
        sudo apt-get update
    - name: One time install for MongoDB
      apt:
        name: mongodb-org
    - name: Setup configuration for MongoDB
      shell: |
        sudo mv /var/www/MongoShard.conf /etc/mongod.conf
        sudo service mongod start
